### ISSUE TITLE
Feature Request: Documentation

### ISSUE THREAD

**Issue by huntwj** [Byron/tui-crates#1]
Hey there,

This project looks really promising, and I think I'd like to leverage your work in my project(s) instead of re-inventing the wheel, license permitting. One thing that would help me in this is improved documentation and/or a Getting Started guide with a Hello World type project. Putting one together might even be just the key for me learning enough about your implementation to make more informed decisions, so I'd be happy to contribute if that would help.

Also, I have some questions about how we can best handle keyboard/mouse/resize events, but that might be best for another thread.

Thanks!

**Comment by Byron** [comment]
Thanks for your interest, here are my thoughts.

#### crosstermion

Even though I started out supporting both termion and crossterm I now lean strongly towards only supporting crossterm in the future. Hence next time termion breaks I would probably remove it entirely for reduced overall complexity. The main reason for this attitude is that termion seems unmaintained whereas crossterm isn't, and it only compiles marginally slower than termion while having seemingly all of its features.

My recommendation is to use the crate if you want, but ideally rely on crossterm more. It might be viable to take code you require as it's really just a few utilities.

#### tui-react

This one opens up `tui` to allow updating/rendering into the terminal at will instead of being confined by the widget abstractions. This one will probably stay with me.


##### Documentation

The crates are meant as support for my other projects and I don't have time to invest into them beyond basic maintenance. In order to make them more useful, it should be possible to extract documentation from how they are used. PRs with (improved) documentation or anything else that come up are definitely welcome.

**Comment by huntwj** [comment]
Great. I think I agree with your take on Termion vs Crossterm moving forward. The potential advantages of Termion just don't see to be outweighed by flexibility of Crossterm except in the most extreme cases.

I'll go ahead and fork this project and explore the possibility of creating some samples for the tui-react.

I'd also like to discuss with you regarding the best practices for handling of incoming Crossterm events. Would that be a discussion for another ticket, or would that be easier in Discord or similar forum?

Thanks again for your time and thoughts.

**Comment by Byron** [comment]
Sorry for the late reply and for skipping over the mouse/keyboard events unintentionally.

> I'll go ahead and fork this project and explore the possibility of creating some samples for the tui-react.

That would be great, I love the idea to review something by creating little code snippets and contribute them back as examples.

> I'd also like to discuss with you regarding the best practices for handling of incoming Crossterm events. Would that be a discussion for another ticket, or would that be easier in Discord or similar forum?

Even though I don't mind doing so in a discussion (open now) real quick my two cents here. The channels provided in `crosstermion` are probably self-explanatory (or would be with an example), and you find example usecases in [criner] and [prodash].
Mouse events should be easy to obtain, maybe right now they are not provided as I didn't need them. Resizing is done by registering [SIGWINCH] and telling the application to redraw. As there are many ways to do this I presume it would be possible to implement one that matches the system in `crosstermion` and add another event to communicate it to the applications event loop. That would probably be behind a feature toggle too as `signal-hook` is needed, the best  crate I know to deal with signals.

I am happy to support there if you would be interested in adding this feature or others.

[criner]: https://github.com/the-lean-crate/criner
[prodash]: https://github.com/byron/prodash
[SIGWINCH]: https://docs.rs/signal-hook/0.3.9/signal_hook/
